import React from 'react';
import { X, FileText, CheckCircle2, Copy, Download } from 'lucide-react';

export default function SarDrawer({ isOpen, onClose, sarData, selectedCaseId }) {
  if (!isOpen) return null;

  const narrativeText = sarData?.narrative || 'No SAR narrative available for this case.';
  const isMandatory = sarData?.file !== false;

  const handleCopy = () => {
    navigator.clipboard.writeText(narrativeText);
  };

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      {/* Dark Overlay Backdrop */}
      <div
        className="fixed inset-0 bg-black/80 backdrop-blur-xs transition-opacity"
        onClick={onClose}
      />

      {/* Slide-over Drawer Panel */}
      <div className="relative w-full max-w-2xl bg-[#050505] border-l border-[#222222] h-full flex flex-col z-10 shadow-2xl transition-transform duration-300">
        {/* Drawer Header */}
        <div className="p-5 border-b border-[#222222] bg-[#0F0F0F] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-[#050505] border border-[#222222]">
              <FileText className="w-5 h-5 text-[#FFFFFF]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-mono text-sm font-bold text-[#FFFFFF] tracking-wider uppercase">
                  SUSPICIOUS ACTIVITY REPORT (SAR)
                </h3>
                <span className={`px-2 py-0.5 text-[10px] font-mono font-bold border ${isMandatory ? 'bg-[#FF3366]/10 text-[#FF3366] border-[#FF3366]/40' : 'bg-[#10B981]/10 text-[#10B981] border-[#10B981]/40'}`}>
                  {isMandatory ? 'MANDATORY FILING' : 'OPTIONAL'}
                </span>
              </div>
              <span className="font-mono text-xs text-[#777777]">
                FinCEN Form 111 Compliance Narrative // Case {selectedCaseId}
              </span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-[#777777] hover:text-[#FFFFFF] border border-[#222222] hover:border-[#FFFFFF] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Action Controls Bar */}
        <div className="px-5 py-3 border-b border-[#222222] bg-[#050505] flex items-center justify-between font-mono text-xs">
          <div className="flex items-center gap-2 text-[#777777]">
            <CheckCircle2 className="w-4 h-4 text-[#10B981]" />
            <span>Format: FinCEN E-Filing Standard v2.4</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-[#0F0F0F] hover:bg-[#1A1A1A] border border-[#222222] text-[#FFFFFF] text-xs font-mono transition-colors"
            >
              <Copy className="w-3.5 h-3.5" />
              Copy Narrative
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-[#FFFFFF] hover:bg-[#CCCCCC] text-[#050505] font-bold text-xs font-mono transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Export .SAR
            </button>
          </div>
        </div>

        {/* Drawer Body - Narrative text in JetBrains Mono font */}
        <div className="flex-1 overflow-y-auto p-6 font-mono text-xs leading-relaxed text-[#FFFFFF] bg-[#050505] select-text">
          <div className="bg-[#0F0F0F] border border-[#222222] p-5 whitespace-pre-wrap font-mono">
            {narrativeText}
          </div>
        </div>

        {/* Drawer Footer */}
        <div className="p-4 border-t border-[#222222] bg-[#0F0F0F] flex items-center justify-between font-mono text-[11px] text-[#777777]">
          <span>Generated by Tark AI Agentic Engine</span>
          <span>Regulatory Audit ID: AUD-{selectedCaseId.replace('HHG-', '')}-2026</span>
        </div>
      </div>
    </div>
  );
}
